apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    app: simple-webapp
spec:
  containers:
    - name: simple-webapp
      image: nginx
      imagePullPolicy: IfNotPresent
      #config single
      env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_COLOR
      #config from
      envFrom:
        - configMapRef:
            name: app-config
      volumeMounts:
        - mountPath: /config
          name: app-config-volume
  volumes:
    - name: app-config-volume
      configMap:
        name: app-config