apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "helm"
  url: "https://argoproj.github.io/argo-helm"
  password: ""
  username: "my-token"
  tlsClientCertData: ""
  tlsClientCertKey: ""