apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    app: simple-webapp
spec:
  containers:
    - name: simple-webapp
      image: nginx
      imagePullPolicy: IfNotPresent
      #config single
      env:
        - name: APP_COLOR
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_Host
      #config from
      envFrom:
        - secretRef:
            name: app-secret
      volumeMounts:
        - mountPath: /config
          name: app-secret-volume
  volumes:
    - name: app-secret-volume
      secret:
        secretName: app-secret