apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-pod
  labels:
    app: web-pod
spec:
  selector:
    matchLabels:
      app: web-pod
  template:
    metadata:
      labels:
        app: web-pod
    spec:
      containers:
        - name: nginx
          image: nginx
