apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web-pod
spec:
  containers:
    - name: web-pod
      image: ubuntu
      command:
        - sleep
        - "3600"
######################
  tolerations: ##kubectl taint nodes node1 app=blue:NoSchedule  <-- node taint 가진경우
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: NoSchedule
######################
  restartPolicy: Always
