apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web-pod
spec:
  containers:
    - name: web-pod
      image: ubuntu
      ports:
        - containerPort: 8080
    - name: log-agent
      image: log-agent
      ports:
        - containerPort: 9000

