stages:
  - build
  - test

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths: 
      - build/

test_artifact:
  image: alpine
  stage: test
  script:
    - test -f build/index.html

unit_tests:
  image: node:22-alpine
  stage: test
  script:
    - npm ci
    - npm test
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml

netlify:
  image: node:22-alpine
  stage: .pre
  script:
    - npm install -g netlify-cli
    - netlify --version