apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  accessModes:
      - ReadWriteOnce
  capacity:
      storage: 1Gi
  hostPath:
    path: /tmp/data
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete

