apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web-pod
spec:
  containers:
    - name: web-pod
      image: ubuntu
      command:
        - sleep
        - "3600"
      volumeMounts:
      - mountPath: /opt
        name: data-volume
  volumes:
  - name: data-volume
    hostPath:
        path: /data
        type: Diretory

